# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Development
pool:
  vmImage: 'windows-latest'

steps:

- script: |
    npm install -g @angular/cli@8.3.29
    npm install
    ng build --prod
  workingDirectory: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile'
  displayName: 'npm install and build'

# - script: |
#     node ./node_modules/@angular/cli/bin/ng build
#   displayName: 'ng build prod'
#   workingDirectory: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile'

# - task: CopyFiles@2
#   displayName: 'Copy Files'
#   inputs:
#     SourceFolder: 'wwwroot/**'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'


# - task: ArchiveFiles@2
#   displayName: 'Archive $(Build.ArtifactStagingDirectory)'
#   inputs:
#     rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist/'
    ArtifactName: 'Helpdesk_Mobile'
