trigger:
- Development

name: $(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(Rev:r)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: build-variables

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\CommonAssembly\SharedAssemblyInfo.cs
      **\CommonAssembly\SharedAssemblyInfo.vb
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    InformationalVersion: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Web
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'

