trigger:
- Development

name: $(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(Rev:r)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: build-variables

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\CommonAssembly\SharedAssemblyInfo.cs
      **\CommonAssembly\SharedAssemblyInfo.vb
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    InformationalVersion: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Web
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'

- task: CopyFiles@2
  displayName: Copy DH-Helpdesk-Web
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/_PublishedWebsites/DH.Helpdesk.Web'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Web'

- task: PublishPipelineArtifact@1
  displayName: Publish Artifact DH-Helpdesk-Web
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Web'
    artifactName: 'DH-Helpdesk-Web'

# #Trying to add Helpdesk-Mobile
- task: NodeTool@0
  inputs:
    versionSpec: '10.18.1'
- script: |
    npm install -g @angular/cli@8.3.29
  workingDirectory: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile'
  displayName: 'npm install cli'
- script: 
    npm install
  workingDirectory: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile'
  displayName: 'npm install'
- script: 
    npm run build_prod --verbose
  workingDirectory: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile'
  displayName: 'ng build prod'

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    Contents: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile/wwwroot/build/**' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile/wwwroot/build'
    ArtifactName: 'Helpdesk_Mobile'