trigger:
- Development

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)" p:OutDir="$(build.artifactStagingDirectory)"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
- task: MSBuild@1
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'

- task: MSBuild@1
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web_SelfService/DH.Helpdesk.SelfService.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'
    

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(build.artifactStagingDirector)'
#     Contents: |
#       **
#     OverWrite: true
#     CleanTargetFolder: true
#     TargetFolder: '$(build.artifactStagingDirector)\DH.Helpdesk.Web'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/_PublishedWebsites/DH.Helpdesk.Web'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Web'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/_PublishedWebsites/DH.Helpdesk.Selfservice'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Selfservice'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/Database/SQLScripts'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\DH-Helpdesk-Database'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Web'
    artifactName: 'DH-Helpdesk-Web'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Database'
    artifactName: 'DH-Helpdesk-Database'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Selfservice'
    artifactName: 'DH-Helpdesk-Selfservice'