trigger:
  tags:
    include:
    - Release-*

name: $(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(Build.SourceVersion)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  solutionExtCaseApi: '**/ExtendedCase/ExtendedCase.Api.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: build-variables
  patch: $[counter(format('{0}.{1}', variables['development.versionMajor'], variables['development.versionMinor'], variables['development.versionSubMinor']), 0)]

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo $(Build.SourceVersion)
      set sourceVersion=$(Build.SourceVersion)
      set sourceVersionSubstring=%sourceVersion:~0,7%
      echo %sourceVersionSubstring%
      echo ##vso[task.setvariable variable=SourceVersionShort]%sourceVersionSubstring%
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##vso[task.setvariable variable=myVar;]foo"
      Write-Host "##vso[task.setvariable variable=ProjectBuildNumber;]$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)"
      Write-Host "##vso[build.updatebuildnumber]$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)"


- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\CommonAssembly\SharedAssemblyInfo.cs
      **\CommonAssembly\SharedAssemblyInfo.vb
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    InformationalVersion: '$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)'
    FileVersionNumber: '$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Web
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.SelfService
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web_SelfService/DH.Helpdesk.SelfService.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'
    
- task: MSBuild@1
  displayName: Build DH.Helpdesk.WebApi
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.WebApi/DH.Helpdesk.WebApi.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.LDAP_AD
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.LDAP-AD/DH.Helpdesk.LDAP_AD.vbproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.LDAP_AD"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Mail2Ticket
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.Mail2Ticket/DH.Helpdesk.Mail2Ticket.vbproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.Mail2Ticket"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Schedule
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.Schedule/DH.Helpdesk.Schedule.vbproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.Schedule"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.TaskScheduler
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.TaskScheduler/DH.Helpdesk.TaskScheduler.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.TaskScheduler"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Upkeeper
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.Upkeeper/DH.Helpdesk.Upkeeper.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.Upkeeper"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.EmailEngine.WinService
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.EmailEngine.WinService/DH.Helpdesk.EmailEngine.WinService.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.EmailEngine.WinService"'
    
- task: MSBuild@1
  displayName: Build DH.Helpdesk.SCCM
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.SCCM/DH.Helpdesk.SCCM.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.SCCM"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.LicenseReporter
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.LicenseReporter/DH.Helpdesk.LicenseReporter.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.LicenseReporter"'


#Copying files
- task: CopyFiles@2
  displayName: Copy DH-Helpdesk-Web
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/_PublishedWebsites/DH.Helpdesk.Web'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Web'

- task: CopyFiles@2
  displayName: Copy DH-Helpdesk-Selfservice
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/_PublishedWebsites/DH.Helpdesk.Selfservice'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Selfservice'

- task: CopyFiles@2
  displayName: Copy DH-Helpdesk-WebApi
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/_PublishedWebsites/DH.Helpdesk.WebApi'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-WebApi'

- task: CopyFiles@2
  displayName: Copy DH-Helpdesk-Database
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/Database/SQLScripts'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\DH-Helpdesk-Database'

- task: PublishPipelineArtifact@1
  displayName: Publish Artifact DH-Helpdesk-Web
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Web'
    artifactName: 'DH-Helpdesk-Web'

- task: PublishPipelineArtifact@1
  displayName: Publish Artifact DH-Helpdesk-Database
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Database'
    artifactName: 'DH-Helpdesk-Database'

- task: PublishPipelineArtifact@1
  displayName: Publish Artifact DH-Helpdesk-Selfservice
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-Selfservice'
    artifactName: 'DH-Helpdesk-Selfservice'
- task: PublishPipelineArtifact@1
  displayName: Publish Artifact DH-Helpdesk-WebApi
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DH-Helpdesk-WebApi'
    artifactName: 'DH-Helpdesk-WebApi'


- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.LDAP-AD
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.LDAP_AD' 
    artifactName: 'DH.Helpdesk-LDAP-AD'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.Mail2Ticket
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Mail2Ticket' 
    artifactName: 'DH.Helpdesk-Mail2Ticket'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.Schedule
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Schedule' 
    artifactName: 'DH.Helpdesk-Schedule'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.TaskScheduler
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.TaskScheduler' 
    artifactName: 'DH.Helpdesk-TaskScheduler'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.Upkeeper
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Upkeeper' 
    artifactName: 'DH.Helpdesk-Upkeeper'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.EmailEngine.WinService
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.EmailEngine.WinService' 
    artifactName: 'DH.Helpdesk.EmailEngine.WinService'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.SCCM
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.SCCM' 
    artifactName: 'DH.Helpdesk.SCCM'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.LicenseReporter
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.LicenseReporter' 
    artifactName: 'DH.Helpdesk.LicenseReporter'

#Ext-Case-Api
- task: NuGetCommand@2
  displayName: Restoring Nugets for ExtendedCase-Api
  inputs:
    restoreSolution: '$(solutionExtCaseApi)'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.ExtendedCase.Api
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/ExtendedCase/ExtendedCase.WebApi/ExtendedCase.WebApi.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'
  
- task: PublishPipelineArtifact@1
  displayName: Publish Artifact DH-Helpdesk-ExtendedCase-WebApi
  inputs:
   targetPath: '$(Build.ArtifactStagingDirectory)/_PublishedWebsites/ExtendedCase.WebApi'
   artifactName: 'DH-Helpdesk-ExtendedCase-WebApi'

#Ext-Case-Web
- task: CopyFiles@2
  displayName: Copy DH-Helpdesk-ExtendedCase-Web
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/ExtendedCase/ExtendedCase.Web/src'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ExtendedCase.Web'
  
- task: PublishPipelineArtifact@1
  displayName: Publish Artifact DH-Helpdesk-ExtendedCase-Web
  inputs:
   targetPath: '$(Build.ArtifactStagingDirectory)/ExtendedCase.Web'
   artifactName: 'DH-Helpdesk-ExtendedCase-Web'

# Building Helpdesk-Mobile
- task: NodeTool@0
  inputs:
    versionSpec: '10.18.1'
- script: |
    npm install -g @angular/cli@8.3.29
  workingDirectory: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile'
  displayName: 'npm install cli for Mobile'
- script: 
    npm install
  workingDirectory: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile'
  displayName: 'npm install for Mobile'
- script: 
    npm run build_prod --verbose
  workingDirectory: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile'
  displayName: 'ng build prod Mobile'

- task: CopyFiles@2
  displayName: 'Copying Files Mobile'
  inputs:
    Contents: '$(System.DefaultWorkingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile/wwwroot/build/**' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publishing Artifact Helpdesk_Mobile'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dhHelpdeskNG/DH.Helpdesk.WebMobile/wwwroot/build'
    ArtifactName: 'Helpdesk_Mobile'

# Building ExtendedCase WebComponents
- task: NodeTool@0
  inputs:
    versionSpec: '10.18.1'
- script: |
    npm install -g @angular/cli@8.3.29
  workingDirectory: '$(System.DefaultWorkingDirectory)/ExtendedCase/ExtendedCase.WebComponent'
  displayName: 'npm install cli ExtendedCase'
- script: 
    npm install
  workingDirectory: '$(System.DefaultWorkingDirectory)/ExtendedCase/ExtendedCase.WebComponent'
  displayName: 'npm install'
- script: 
    npm run build-test --verbose
  workingDirectory: '$(System.DefaultWorkingDirectory)/ExtendedCase/ExtendedCase.WebComponent'
  displayName: 'ng build prod ExtendedCase'

- task: CopyFiles@2
  displayName: 'Copy Files ExtendedCase.WebComponent'
  inputs:
    Contents: '$(System.DefaultWorkingDirectory)/ExtendedCase/ExtendedCase.WebComponent/dist/**' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publishing Artifact Helpdesk_ExtendedCase_WebComponent'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/ExtendedCase/ExtendedCase.WebComponent/dist'
    ArtifactName: 'Helpdesk_ExtendedCase_WebComponent'