trigger:
- Master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Web
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'


- task: MSBuild@1
  displayName: Build DH.Helpdesk.SelfService
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web_SelfService/DH.Helpdesk.SelfService.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'


- task: MSBuild@1
  displayName: Build DH.Helpdesk.WebApi
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.WebApi/DH.Helpdesk.WebApi.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.LDAP_AD
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.LDAP-AD/DH.Helpdesk.LDAP_AD.vbproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.LDAP_AD"'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Mail2Ticket
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.Mail2Ticket/DH.Helpdesk.Mail2Ticket.vbproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.Mail2Ticket"'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.LDAP-AD
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.LDAP_AD' 
    artifactName: 'DH.Helpdesk-LDAP-AD'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.Mail2Ticket
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Mail2Ticket' 
    artifactName: 'DH.Helpdesk-Mail2Ticket'


- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.Schedule
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Schedule' 
    artifactName: 'DH.Helpdesk-Schedule'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.TaskScheduler
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.TaskScheduler' 
    artifactName: 'DH.Helpdesk-TaskScheduler'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.Upkeeper
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Upkeeper' 
    artifactName: 'DH.Helpdesk-Upkeeper'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.EmailEngine.WinService
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.EmailEngine.WinService' 
    artifactName: 'DH.Helpdesk.EmailEngine.WinService'