trigger:
- Master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Web
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)"'--