# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- Development

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)" p:OutDir="$(build.artifactStagingDirectory)"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
- task: MSBuild@1
  inputs:
    msbuildVersion: '16.0'  
    solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:OutDir="$(build.artifactStagingDirectory)"'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.artifactStagingDirector)'
    Contents: |
      **
    OverWrite: true
    CleanTargetFolder: true
    TargetFolder: '$(build.artifactStagingDirector)\DH.Helpdesk.Web'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(Build.SourcesDirectory)'
#     Contents: '**/dhHelpdesk_NG.Web/Properties/PublishProfiles/DH.Helpdesk.Web.Release.pubxml'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Web'

- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts-Web
  inputs:
    pathtoPublish: $(build.artifactStagingDirector)\DH.Helpdesk.Web' 
    artifactName: 'DH.Helpdesk.Web'