# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Master
name: $(release.versionMajor).$(relase.versionMinor).$(release.versionSubMinor).$(Rev:r).$(Build.SourceVersion)
pool:
  vmImage: 'windows-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.18.1'
- script: |
    npm install -g @angular/cli@8.3.29
  workingDirectory: '$(System.DefaultWorkingDirectory)/ExtendedCase/ExtendedCase.WebComponent'
  displayName: 'npm install cli'
- script: 
    npm install
  workingDirectory: '$(System.DefaultWorkingDirectory)/ExtendedCase/ExtendedCase.WebComponent'
  displayName: 'npm install'
- script: 
    npm run build-test --verbose
  workingDirectory: '$(System.DefaultWorkingDirectory)/ExtendedCase/ExtendedCase.WebComponent'
  displayName: 'ng build prod'

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    Contents: '$(System.DefaultWorkingDirectory)/ExtendedCase/ExtendedCase.WebComponent/dist/**' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/ExtendedCase/ExtendedCase.WebComponent/dist'
    ArtifactName: 'Helpdesk_ExtendedCase_WebComponent'
