trigger:
  tags:
    include:
    - Release-*

name: $(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(Build.SourceVersion)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  solutionExtCaseApi: '**/ExtendedCase/ExtendedCase.Api.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: build-variables
  patch: $[counter(format('{0}.{1}', variables['development.versionMajor'], variables['development.versionMinor'], variables['development.versionSubMinor']), 0)]
  token: 'kkd2szyqmr5xvuwybvfpm3l3u2oqsyiftc46mrw3wudn6sja7b4a'

steps:
  - script: |

      echo $(System.AccessToken) | az devops login
      az pipelines variable-group variable update --group-id 24 \
        --name tessanTestar \
        --value "1234" \
        --org https://dev.azure.com/dhsolutionsab \
        --project Dh-DHHelpdesk
    displayName: 'Update variable inside a variable group'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)