trigger:
  tags:
    include:
    - Release-*

name: $(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(Build.SourceVersion)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: build-variables
  patch: $[counter(format('{0}.{1}', variables['development.versionMajor'], variables['development.versionMinor'], variables['development.versionSubMinor']), 0)]

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo $(Build.SourceVersion)
      set sourceVersion=$(Build.SourceVersion)
      set sourceVersionSubstring=%sourceVersion:~0,7%
      echo %sourceVersionSubstring%
      echo ##vso[task.setvariable variable=SourceVersionShort]%sourceVersionSubstring%
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##vso[task.setvariable variable=myVar;]foo"
      Write-Host "##vso[task.setvariable variable=ProjectBuildNumber;]$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)"
      Write-Host "##vso[build.updatebuildnumber]$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)"

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Mail2Ticket
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.Mail2Ticket/DH.Helpdesk.Mail2Ticket.vbproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.Mail2Ticket"'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.Mail2Ticket
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Mail2Ticket' 
    artifactName: 'DH.Helpdesk-Mail2Ticket'