# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Development

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NuGetToolInstaller@1

# - task: DotNetCoreCLI@2
#   displayName: dotnet restore
#   inputs:
#     command: restore
#     projects: '**/*.*proj'
#     includeNuGetOrg: true
#     restoreDirectory: '$(build.artifactStagingDirectory)'
    
# - task: NuGetCommand@2
#   inputs:
#     command: 'restore'
#     #restoreSolution: '**\DH.Helpdesk.Mail2Ticket\packages.config'
#     feedsToUse: 'select'
#     restoreDirectory: '$(build.artifactStagingDirectory)'
#     includeNuGetOrg: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**\dhHelpdesk_NG.Common/packages.config'
    includeNuGetOrg: true
    
- task: VSBuild@1
  inputs:
    solution: '**\DH.Helpdesk.Mail2Ticket.vbproj'
    #msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true'    