# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  tags:
    include:
    - Release
  branches:
    include:
    - Development


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildVersion: $(AssemblyInfo.AssemblyInformationalVersion)

steps:
- task: NuGetToolInstaller@1

- task: AssembyInfoReader@3
  inputs:
    searchPattern: '**\CommonAssembly\SharedAssemblyInfo.cs'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: '1e2f294e-d4e3-4681-bb74-833f682abc75'

- task: MSBuild@1
  inputs:
    solution: '**/dhHelpdesk_NG.Web/DH.Helpdesk.Web.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:OutDir="$(build.artifactStagingDirectory)"'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/dhHelpdeskNG/DH.Helpdesk.LDAP-AD/bin/$(buildConfiguration)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/DH.Helpdesk.LDAP-AD'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/dhHelpdeskNG/DH.Helpdesk.Mail2Ticket/bin/$(buildConfiguration)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/DH.Helpdesk.Mail2Ticket'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/dhHelpdeskNG/DH.Helpdesk.Upkeeper/bin/$(buildConfiguration)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/DH.Helpdesk.Upkeeper'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/dhHelpdeskNG/DH.Helpdesk.TaskScheduler/bin/$(buildConfiguration)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/DH.Helpdesk.TaskScheduler'
    

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/dhHelpdeskNG/DH.Helpdesk.EmailEngine.WinService/bin/$(buildConfiguration)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/DH.Helpdesk.EmailEngine.WinService'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/dhHelpdeskNG/DH.Helpdesk.Schedule/bin/$(buildConfiguration)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/DH.Helpdesk.Schedule'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/dhHelpdeskNG/dhHelpdesk_NG.Web'
    Contents: 'dhHelpdesk_NG.Web/Properties/PublishProfiles/DH.Helpdesk.Web.Release.pubxml'
    TargetFolder: '$(build.artifactstagingdirectory)/dhHelpdesk_NG.Web'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts-LDAP-AD
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.LDAP-AD' 
    artifactName: 'DH.Helpdesk.LDAP-AD'

- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts-LDAP-AD
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Mail2Ticket' 
    artifactName: 'DH.Helpdesk.Mail2Ticket'

- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts-Upkeeper
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Upkeeper' 
    artifactName: 'DH.Helpdesk.UpKeeper'

- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts-TaskScheduler
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.TaskScheduler' 
    artifactName: 'DH.Helpdesk.TaskScheduler'

- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts-EmailEngine
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.EmailEngine.WinService' 
    artifactName: 'DH.Helpdesk.EmailEngine.WinService'

- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts-Schedule
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Schedule' 
    artifactName: 'DH.Helpdesk.Schedule'

- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts-Web
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/dhHelpdesk_NG.Web' 
    artifactName: 'dhHelpdesk_NG.Web'