trigger:
  tags:
    include:
    - Release-*

name: $(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(Build.SourceVersion)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DH.Helpdesk.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: build-variables
  patch: $[counter(format('{0}.{1}', variables['development.versionMajor'], variables['development.versionMinor'], variables['development.versionSubMinor']), 0)]

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo $(Build.SourceVersion)
      set sourceVersion=$(Build.SourceVersion)
      set sourceVersionSubstring=%sourceVersion:~0,7%
      echo %sourceVersionSubstring%
      echo ##vso[task.setvariable variable=SourceVersionShort]%sourceVersionSubstring%
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##vso[task.setvariable variable=myVar;]foo"
      Write-Host "##vso[task.setvariable variable=ProjectBuildNumber;]$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)"
      Write-Host "##vso[build.updatebuildnumber]$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)"


- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\CommonAssembly\SharedAssemblyInfo.cs
      **\CommonAssembly\SharedAssemblyInfo.vb
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    InformationalVersion: '$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)'
    FileVersionNumber: '$(development.versionMajor).$(development.versionMinor).$(development.versionSubMinor).$(development.versionRevision).$(SourceVersionShort)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: MSBuild@1
  displayName: Build DH.Helpdesk.Upkeeper
  inputs:
    msbuildVersion: '17.0'  
    solution: '**/dhHelpdeskNG/DH.Helpdesk.Upkeeper/DH.Helpdesk.Upkeeper.csproj'
    msbuildArguments: '/p:TargetFrameworkVersion=v4.7.2 /p:SkipInvalidConfigurations=true /p:OutDir="$(Build.ArtifactStagingDirectory)\DH.Helpdesk.Upkeeper"'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact DH.Helpdesk.Upkeeper
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/DH.Helpdesk.Upkeeper' 
    artifactName: 'DH.Helpdesk-Upkeeper'