namespace DH.Helpdesk.Web.NinjectModules.Common
{
    using DH.Helpdesk.Dal.Repositories;
    using DH.Helpdesk.Dal.Repositories.ADFS;
    using DH.Helpdesk.Dal.Repositories.ADFS.Concrete;
    using DH.Helpdesk.Dal.Repositories.BusinessRules;
    using DH.Helpdesk.Dal.Repositories.BusinessRules.Concrete;
    using DH.Helpdesk.Dal.Repositories.Cases;
    using DH.Helpdesk.Dal.Repositories.Cases.Concrete;
    using DH.Helpdesk.Dal.Repositories.CaseDocument;
    using DH.Helpdesk.Dal.Repositories.CaseDocument.Concrete;
    using DH.Helpdesk.Dal.Repositories.Changes;
    using DH.Helpdesk.Dal.Repositories.Changes.Concrete;
    using DH.Helpdesk.Dal.Repositories.Computers;
    using DH.Helpdesk.Dal.Repositories.Computers.Concrete;
    using DH.Helpdesk.Dal.Repositories.Concrete;
    using DH.Helpdesk.Dal.Repositories.Faq;
    using DH.Helpdesk.Dal.Repositories.Faq.Concrete;
    using DH.Helpdesk.Dal.Repositories.Inventory;
    using DH.Helpdesk.Dal.Repositories.Inventory.Concrete;
    using DH.Helpdesk.Dal.Repositories.Invoice;
    using DH.Helpdesk.Dal.Repositories.Invoice.Concrete;
    using DH.Helpdesk.Dal.Repositories.MailTemplates;
    using DH.Helpdesk.Dal.Repositories.MailTemplates.Concrete;
    using DH.Helpdesk.Dal.Repositories.Modules;
    using DH.Helpdesk.Dal.Repositories.Modules.Concrete;
    using DH.Helpdesk.Dal.Repositories.Notifiers;
    using DH.Helpdesk.Dal.Repositories.Notifiers.Concrete;
    using DH.Helpdesk.Dal.Repositories.Printers;
    using DH.Helpdesk.Dal.Repositories.Printers.Concrete;
    using DH.Helpdesk.Dal.Repositories.Problem;
    using DH.Helpdesk.Dal.Repositories.Problem.Concrete;
    using DH.Helpdesk.Dal.Repositories.Projects;
    using DH.Helpdesk.Dal.Repositories.Projects.Concrete;
    using DH.Helpdesk.Dal.Repositories.Questionnaire;
    using DH.Helpdesk.Dal.Repositories.Questionnaire.Concrete;
    using DH.Helpdesk.Dal.Repositories.ReportService;
    using DH.Helpdesk.Dal.Repositories.ReportService.Concrete;
    using DH.Helpdesk.Dal.Repositories.Servers;
    using DH.Helpdesk.Dal.Repositories.Servers.Concrete;
    using DH.Helpdesk.Dal.Repositories.Users;
    using DH.Helpdesk.Dal.Repositories.Users.Concrete;
    using DH.Helpdesk.Dal.Repositories.WorkstationModules;
    using DH.Helpdesk.Dal.Repositories.WorkstationModules.Concrete;
    using Ninject.Modules;

    public sealed class RepositoriesModule : NinjectModule
    {
        #region Public Methods and Operators

        public override void Load()
        {
            this.Bind<IChangeCategoryRepository>().To<ChangeCategoryRepository>();
            this.Bind<IChangeChangeGroupRepository>().To<ChangeChangeGroupRepository>();
            this.Bind<IChangeChangeRepository>().To<ChangeChangeRepository>();
            this.Bind<IChangeContactRepository>().To<ChangeContactRepository>();
            this.Bind<IChangeCouncilRepository>().To<ChangeCouncilRepository>();
            this.Bind<IChangeDepartmentRepository>().To<ChangeDepartmentRepository>();
            this.Bind<IChangeEmailLogRepository>().To<ChangeEmailLogRepository>();
            this.Bind<IChangeFieldSettingRepository>().To<ChangeFieldSettingRepository>();
            this.Bind<IChangeFileRepository>().To<ChangeFileRepository>();
            this.Bind<IChangeGroupRepository>().To<ChangeGroupRepository>();
            this.Bind<IChangeHistoryRepository>().To<ChangeHistoryRepository>();
            this.Bind<IChangeImplementationStatusRepository>().To<ChangeImplementationStatusRepository>();
            this.Bind<IChangeLogRepository>().To<ChangeLogRepository>();
            this.Bind<IChangeObjectRepository>().To<ChangeObjectRepository>();
            this.Bind<IChangePriorityRepository>().To<ChangePriorityRepository>();
            this.Bind<IChangeRepository>().To<ChangeRepository>();
            this.Bind<IChangeStatusRepository>().To<ChangeStatusRepository>();

            this.Bind<IFaqCategoryLanguageRepository>().To<FaqCategoryLanguageRepository>();
            this.Bind<IFaqCategoryRepository>().To<FaqCategoryRepository>();
            this.Bind<IFaqFileRepository>().To<FaqFileRepository>();
            this.Bind<IFaqLanguageRepository>().To<FaqLanguageRepository>();
            this.Bind<IFaqRepository>().To<FaqRepository>();

            this.Bind<ILinkGroupRepository>().To<LinkGroupRepository>();
            this.Bind<ILinkRepository>().To<LinkRepository>();

            this.Bind<INotifierFieldSettingLanguageRepository>().To<NotifierFieldSettingLanguageRepository>();
            this.Bind<INotifierFieldSettingRepository>().To<NotifierFieldSettingRepository>();
            this.Bind<INotifierGroupRepository>().To<NotifierGroupRepository>();
            this.Bind<INotifierRepository>().To<NotifierRepository>();

            this.Bind<IProblemEMailLogRepository>().To<ProblemEMailLogRepository>();
            this.Bind<IProblemLogRepository>().To<ProblemLogRepository>();
            this.Bind<IProblemRepository>().To<ProblemRepository>();

            this.Bind<IProjectCollaboratorRepository>().To<ProjectCollaboratorRepository>();
            this.Bind<IProjectFileRepository>().To<ProjectFileRepository>();
            this.Bind<IProjectLogRepository>().To<ProjectLogRepository>();
            this.Bind<IProjectRepository>().To<ProjectRepository>();
            this.Bind<IProjectScheduleRepository>().To<ProjectScheduleRepository>();

            this.Bind<ICircularRepository>().To<CircularRepository>();
            this.Bind<IQuestionnaireQuestionOptionRepository>().To<QuestionnaireQuestionOptionRepository>();
            this.Bind<IQuestionnaireQuestionRepository>().To<QuestionnaireQuestionRepository>();
            this.Bind<IQuestionnaireRepository>().To<QuestionnaireRepository>();

            this.Bind<IUserEmailRepository>().To<UserEmailRepository>();
            this.Bind<IEmailGroupEmailRepository>().To<EmailGroupEmailRepository>();
            this.Bind<IAccountRepository>().To<AccountRepository>();
            this.Bind<IAccountActivityGroupRepository>().To<AccountActivityGroupRepository>();
            this.Bind<IAccountActivityRepository>().To<AccountActivityRepository>();
            this.Bind<IAccountEMailLogRepository>().To<AccountEMailLogRepository>();
            this.Bind<IAccountFieldSettingsRepository>().To<AccountFieldSettingsRepository>();
            this.Bind<IAccountTypeRepository>().To<AccountTypeRepository>();
            this.Bind<IApplicationRepository>().To<ApplicationRepository>();
            this.Bind<IBuildingRepository>().To<BuildingRepository>();
            this.Bind<IBulletinBoardRepository>().To<BulletinBoardRepository>();
            this.Bind<ICalendarRepository>().To<CalendarRepository>();
            this.Bind<ICaseRepository>().To<CaseRepository>();
            this.Bind<ICaseFieldSettingLanguageRepository>().To<CaseFieldSettingLanguageRepository>();
            this.Bind<ICaseFieldSettingRepository>().To<CaseFieldSettingRepository>();
            this.Bind<ICaseFileRepository>().To<CaseFileRepository>();
            this.Bind<ICaseHistoryRepository>().To<CaseHistoryRepository>();
            this.Bind<ICaseInvoiceRowRepository>().To<CaseInvoiceRowRepository>();
            this.Bind<ICaseQuestionCategoryRepository>().To<CaseQuestionCategoryRepository>();
            this.Bind<ICaseQuestionHeaderRepository>().To<CaseQuestionHeaderRepository>();
            this.Bind<ICaseQuestionRepository>().To<CaseQuestionRepository>();
            this.Bind<ICaseSearchRepository>().To<CaseSearchRepository>();
            this.Bind<ICaseSettingRepository>().To<CaseSettingRepository>();
            this.Bind<ICaseSolutionCategoryRepository>().To<CaseSolutionCategoryRepository>();
            this.Bind<ICaseSolutionRepository>().To<CaseSolutionRepository>();
            this.Bind<ICaseSolutionScheduleRepository>().To<CaseSolutionScheduleRepository>();
            this.Bind<ICaseTypeRepository>().To<CaseTypeRepository>();
            this.Bind<ICategoryRepository>().To<CategoryRepository>();
            this.Bind<IChecklistActionRepository>().To<ChecklistActionRepository>();
            this.Bind<IChecklistRepository>().To<ChecklistRepository>();
            this.Bind<IChecklistRowRepository>().To<ChecklistRowRepository>();
            this.Bind<ICheckListServiceRepository>().To<CheckListServiceRepository>();
            this.Bind<IChecklistRepository>().To<ChecklistRepository>();
            this.Bind<IChecklistsRepository>().To<ChecklistsRepository>();            
            this.Bind<IContractCategoryRepository>().To<ContractCategoryRepository>();
            this.Bind<IContractFieldSettingsRepository>().To<ContractFieldSettingsRepository>();
            this.Bind<IContractFileRepository>().To<ContractFileRepository>();
            this.Bind<IContractHistoryRepository>().To<ContractHistoryRepository>();
            this.Bind<IContractLogRepository>().To<ContractLogRepository>();
            this.Bind<IContractRepository>().To<ContractRepository>();
            this.Bind<ICountryRepository>().To<CountryRepository>();
            this.Bind<ICurrencyRepository>().To<CurrencyRepository>();
            this.Bind<ICustomerRepository>().To<CustomerRepository>();
            this.Bind<ICustomerUserRepository>().To<CustomerUserRepository>();
            this.Bind<IDailyReportRepository>().To<DailyReportRepository>();
            this.Bind<IDailyReportSubjectRepository>().To<DailyReportSubjectRepository>();
            this.Bind<IDepartmentRepository>().To<DepartmentRepository>();
            this.Bind<IDepartmentUserRepository>().To<DepartmentUserRepository>();
            this.Bind<IDivisionRepository>().To<DivisionRepository>();
            this.Bind<IDocumentationRepository>().To<DocumentationRepository>();
            this.Bind<IDocumentCategoryRepository>().To<DocumentCategoryRepository>();
            this.Bind<IDocumentRepository>().To<DocumentRepository>();
            this.Bind<IDomainRepository>().To<DomainRepository>();
            this.Bind<IEmailGroupRepository>().To<EmailGroupRepository>();
            this.Bind<IEmailLogRepository>().To<EmailLogRepository>();
            this.Bind<IEmploymentTypeRepository>().To<EmploymentTypeRepository>();
            this.Bind<IFinishingCauseCategoryRepository>().To<FinishingCauseCategoryRepository>();
            this.Bind<IFinishingCauseRepository>().To<FinishingCauseRepository>();
            this.Bind<IFloorRepository>().To<FloorRepository>();
            this.Bind<IFormFieldRepository>().To<FormFieldRepository>();
            this.Bind<IFormFieldValueRepository>().To<FormFieldValueRepository>();
            this.Bind<IFormRepository>().To<FormRepository>();
            this.Bind<IGlobalSettingRepository>().To<GlobalSettingRepository>();
            this.Bind<IHolidayRepository>().To<HolidayRepository>();
            this.Bind<IHolidayHeaderRepository>().To<HolidayHeaderRepository>();
            this.Bind<IImpactRepository>().To<ImpactRepository>();
            this.Bind<IInfoTextRepository>().To<InfoTextRepository>();
            this.Bind<IInvoiceHeaderRepository>().To<InvoiceHeaderRepository>();
            this.Bind<IInvoiceRowRepository>().To<InvoiceRowRepository>();
            this.Bind<ILanguageRepository>().To<LanguageRepository>();
            this.Bind<ILicenseFileRepository>().To<LicenseFileRepository>();
            this.Bind<ILicenseRepository>().To<LicenseRepository>();
            this.Bind<ILocalAdminRepository>().To<LocalAdminRepository>();
            this.Bind<ILogFileRepository>().To<LogFileRepository>();
            this.Bind<ILogicalDriveRepository>().To<LogicalDriveRepository>();
            this.Bind<ILogProgramRepository>().To<LogProgramRepository>();
            this.Bind<ILogRepository>().To<LogRepository>();
            this.Bind<ILogSyncRepository>().To<LogSyncRepository>();
            this.Bind<IMailTemplateIdentifierRepository>().To<MailTemplateIdentifierRepository>();
            this.Bind<IMailTemplateRepository>().To<MailTemplateRepository>();
            this.Bind<IMailTemplateLanguageRepository>().To<MailTemplateLanguageRepository>();
            this.Bind<IManufacturerRepository>().To<ManufacturerRepository>();
            this.Bind<INICRepository>().To<NICRepository>();
            this.Bind<IOperationLogCategoryRepository>().To<OperationLogCategoryRepository>();
            this.Bind<IOperationLogRepository>().To<OperationLogRepository>();
            this.Bind<IOperationObjectRepository>().To<OperationObjectRepository>();
            this.Bind<IOrderEMailLogRepository>().To<OrderEMailLogRepository>();
            this.Bind<IOrderFieldSettingsRepository>().To<OrderFieldSettingsRepository>();
            this.Bind<IOrderLogRepository>().To<OrderLogRepository>();
            this.Bind<IOrderRepository>().To<OrderRepository>();
            this.Bind<IOrderStateRepository>().To<OrderStateRepository>();
            this.Bind<IOrderTypeRepository>().To<OrderTypeRepository>();
            this.Bind<IOULanguageRepository>().To<OULanguageRepository>();
            this.Bind<IOrganizationUnitRepository>().To<OrganizationUnitRepository>();
            this.Bind<IPermissionLanguageRepository>().To<PermissionLanguageRepository>();
            this.Bind<IPermissionRepository>().To<PermissionRepository>();
            this.Bind<IPrinterFieldSettingsRepository>().To<PrinterFieldSettingsRepository>();
            this.Bind<IPrinterRepository>().To<PrinterRepository>();
            this.Bind<IPriorityImpactUrgencyRepository>().To<PriorityImpactUrgencyRepository>();
            this.Bind<IPriorityLanguageRepository>().To<PriorityLanguageRepository>();
            this.Bind<IPriorityRepository>().To<PriorityRepository>();
            this.Bind<IProcessorRepository>().To<ProcessorRepository>();
            this.Bind<IProductAreaQuestionRepository>().To<ProductAreaQuestionRepository>();
            this.Bind<IProductAreaQuestionVersionRepository>().To<ProductAreaQuestionVersionRepository>();
            this.Bind<IProductAreaRepository>().To<ProductAreaRepository>();
            this.Bind<IProductRepository>().To<ProductRepository>();
            this.Bind<IProgramRepository>().To<ProgramRepository>();
            this.Bind<IQuestionCategoryRepository>().To<QuestionCategoryRepository>();
            this.Bind<IQuestionGroupRepository>().To<QuestionGroupRepository>();
            this.Bind<IQuestionRegistrationRepository>().To<QuestionRegistrationRepository>();
            this.Bind<IQuestionRepository>().To<QuestionRepository>();
            this.Bind<IRegionLanguageRepository>().To<RegionLanguageRepository>();
            this.Bind<IRegionRepository>().To<RegionRepository>();
            this.Bind<IReportCustomerRepository>().To<ReportCustomerRepository>();
            this.Bind<IReportRepository>().To<ReportRepository>();
            this.Bind<IRoomRepository>().To<RoomRepository>();
            this.Bind<ISettingRepository>().To<SettingRepository>();
            this.Bind<IStandardTextRepository>().To<StandardTextRepository>();
            this.Bind<IStateSecondaryRepository>().To<StateSecondaryRepository>();
            this.Bind<IStatusRepository>().To<StatusRepository>();
            this.Bind<ISupplierRepository>().To<SupplierRepository>();
            this.Bind<ISystemRepository>().To<SystemRepository>();
            this.Bind<ITextTranslationRepository>().To<TextTranslationRepository>();
            this.Bind<ITextRepository>().To<TextRepository>();
            this.Bind<ITextTypeRepository>().To<TextTypeRepository>();
            this.Bind<ITimeRegistrationRepository>().To<TimeRegistrationRepository>();
            this.Bind<ITimeTypeRepository>().To<TimeTypeRepository>();
            this.Bind<IUrgencyLanguageRepository>().To<UrgencyLanguageRepository>();
            this.Bind<IUrgencyRepository>().To<UrgencyRepository>();
            this.Bind<IUserGroupRepository>().To<UserGroupRepository>();
            this.Bind<IUserRepository>().To<UserRepository>();
            this.Bind<IUserRoleRepository>().To<UserRoleRepository>();
            this.Bind<IUsersPasswordHistoryRepository>().To<UsersPasswordHistoryRepository>();
            this.Bind<IUserWorkingGroupRepository>().To<UserWorkingGroupRepository>();
            this.Bind<IVendorRepository>().To<VendorRepository>();
            this.Bind<IWatchDateCalendarRepository>().To<WatchDateCalendarRepository>();
            this.Bind<IWatchDateCalendarValueRepository>().To<WatchDateCalendarValueRepository>();
            this.Bind<IWorkingGroupRepository>().To<WorkingGroupRepository>();
            this.Bind<IModuleRepository>().To<ModuleRepository>();
            this.Bind<IUserModuleRepository>().To<UserModuleRepository>();
            this.Bind<IRAMRepository>().To<RAMRepository>();
            this.Bind<ISoftwareRepository>().To<SoftwareRepository>();
            this.Bind<IOperatingSystemRepository>().To<OperatingSystemRepository>();
            this.Bind<IInventoryFieldSettingsRepository>().To<InventoryFieldSettingsRepository>();
            this.Bind<IInventoryDynamicFieldSettingsRepository>().To<InventoryDynamicFieldSettingsRepository>();
            this.Bind<IInventoryTypePropertyValueRepository>().To<InventoryTypePropertyValueRepository>();
            this.Bind<IInventoryRepository>().To<InventoryRepository>();
            this.Bind<IInventoryTypeRepository>().To<InventoryTypeRepository>();
            this.Bind<IServerFieldSettingsRepository>().To<ServerFieldSettingsRepository>();
            this.Bind<IServerLogicalDriveRepository>().To<ServerLogicalDriveRepository>();
            this.Bind<IServerRepository>().To<ServerRepository>();
            this.Bind<IServerSoftwareRepository>().To<ServerSoftwareRepository>();
            this.Bind<IComputerFieldSettingsRepository>().To<ComputerFieldSettingsRepository>();
            this.Bind<IComputerHistoryRepository>().To<ComputerHistoryRepository>();
            this.Bind<IComputerLogRepository>().To<ComputerLogRepository>();
            this.Bind<IComputerModelRepository>().To<ComputerModelRepository>();
            this.Bind<IComputerRepository>().To<ComputerRepository>();
            this.Bind<IComputerTypeRepository>().To<ComputerTypeRepository>();
            this.Bind<IComputerUsersRepository>().To<ComputerUsersRepository>();
            this.Bind<IComputerUserLogRepository>().To<ComputerUserLogRepository>();
            this.Bind<IComputerUsersBlackListRepository>().To<ComputerUsersBlackListRepository>();
            this.Bind<IComputerInventoryRepository>().To<ComputerInventoryRepository>();
            this.Bind<ICausingPartRepository>().To<CausingPartRepository>();
            this.Bind<IInvoiceArticleUnitRepository>().To<InvoiceArticleUnitRepository>();
            this.Bind<IInvoiceArticleRepository>().To<InvoiceArticleRepository>();
            this.Bind<ICaseInvoiceArticleRepository>().To<CaseInvoiceArticleRepository>();
            this.Bind<ICaseInvoiceSettingsRepository>().To<CaseInvoiceSettingsRepository>();
            this.Bind<IOperationLogEMailLogRepository>().To<OperationLogEMailLogRepository>();
            this.Bind<ICaseSolutionSettingRepository>().To<CaseSolutionSettingRepository>();
            this.Bind<IModulesRepository>().To<ModulesRepository>();
            this.Bind<IADFSRepository>().To<ADFSRepository>();
            this.Bind<IRegistrationSourceCustomerRepository>().To<RegistrationSourceCustomerRepository>();
            this.Bind<ICaseLockRepository>().To<CaseLockRepository>();
            this.Bind<IReportServiceRepository>().To<ReportServiceRepository>();
            this.Bind<ICaseFilterFavoriteRepository>().To<CaseFilterFavoriteRepository>();
            this.Bind<IReportFavoriteRepository>().To<ReportFavoriteRepository>();
            this.Bind<IMail2TicketRepository>().To<Mail2TicketRepository>();
            this.Bind<IBusinessRuleRepository>().To<BusinessRuleRepository>();
            this.Bind<ICaseFollowUpRepository>().To<CaseFollowUpRepository>();
            this.Bind<ICaseExtraFollowersRepository>().To<CaseExtraFollowersRepository>();
			this.Bind<IInvoiceRepository>().To<InvoiceRepository>();
            this.Bind<ICaseSolutionConditionRepository>().To<CaseSolutionConditionRepository>();
            this.Bind<IExtendedCaseFormRepository>().To<ExtendedCaseFormRepository>();
            this.Bind<IExtendedCaseDataRepository>().To<ExtendedCaseDataRepository>();
            this.Bind<ICaseDocumentRepository>().To<CaseDocumentRepository>();
            this.Bind<ICaseDocumentConditionRepository>().To<CaseDocumentConditionRepository>();
            this.Bind<IExtendedCaseValueRepository>().To<ExtendedCaseValueRepository>();
        }

        #endregion
    }
}