// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DH.Helpdesk.Services.BusinessLogic.MailTools.TemplateFormatters
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\mg\Documents\Projects\Datahalland\dh-helpdesk\dhHelpdeskNG\dhHelpdesk_NG.Service\BusinessLogic\MailTools\TemplateFormatters\SurveyTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class SurveyTemplate : SurveyTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<div><table><tr><td><a href=\"");
            
            #line 1 "C:\Users\mg\Documents\Projects\Datahalland\dh-helpdesk\dhHelpdeskNG\dhHelpdesk_NG.Service\BusinessLogic\MailTools\TemplateFormatters\SurveyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VoteGoodLink));
            
            #line default
            #line hidden
            this.Write("\">\r\n\t<img alt=\"");
            
            #line 2 "C:\Users\mg\Documents\Projects\Datahalland\dh-helpdesk\dhHelpdeskNG\dhHelpdesk_NG.Service\BusinessLogic\MailTools\TemplateFormatters\SurveyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VoteGoodText));
            
            #line default
            #line hidden
            this.Write("\" src=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgI" +
                    "CAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgM" +
                    "DAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz" +
                    "/wAARCAAfAB4DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgE" +
                    "DAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJic" +
                    "oKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqK" +
                    "jpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwE" +
                    "AAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJ" +
                    "BUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVld" +
                    "YWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcb" +
                    "HyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD8YPgX8HPEX7ZnxQ0fwT4" +
                    "c0C91jxvrj+TYtZQ/64qu52n/AIVRF+Z5f4VBZulfrj+zb/waQeG7Dw3Bc/GT4nazd6vKm6TTfB0MUMF" +
                    "m3937Vco/m/8AfqOuv/4NT/2VdK8EfspeLPjDNZxN4m8aa0/h+zu2HzWunWqo7LEw+ZPNn8zf/wBcYm/" +
                    "gr7H+CP7RXxV8Xf8ABT745/DTW/DUVl8JvBHhrQ7/AMNaounPEtxczwW7sv2j/lv5vm3Xy/8ALL7DtXb" +
                    "tl3/y/wCIniJnmMxWY4Lh+vGhTwNNzm72lPllyz6Nq01KKUeV80buT51E+oy/L8PTp06uJjzOo7JdF2P" +
                    "hP9oX/g0i8H6x4Znm+EfxQ8Q6Xrkas0Fj4uigu7a8b+FGntUTyP8Ae2St/sV+OH7UH7L/AI4/Y5+MOpe" +
                    "BPiBod14f8R6U3zwsw8u4jP3ZopR8ksTYyrLwenbFf0//ALaHx/8Aiz8Iv2mP2Y/Dvw88KprfhH4keNZ" +
                    "9H8eXLaf9rbTdPRbf5lk/5YKsUt5c7v8Apx/ueajeXf8ABbT/AIJdwf8ABSH4W+D59NEGneNvCmpmKLU" +
                    "WAEjabLDIZIXzgN+/SNl/u4fHLtXk8F+LGc5Lh8DjOK8RCphcXCc735pU1GahzN25muaUbpuekm1KPs3" +
                    "CWmNyuhW9osJG0oW9Hf8Ar+rnh3/Bqf8AtNaZ48/Y68VfCqS6jXxJ4I1ttXitf45tOukHzr/e23Al3f3" +
                    "d8X95a++fiH+1HF8CviLcWHxEls/DfgG/iim0DxTPK0Okwz7Ns9lfSt+6tpd/zRSvtilWbav72Jt38o3" +
                    "7Mf7Tvjb9jz4yaT47+H+tT6H4m0h8xSL80c0bfeilT7skTjhkbg1+z/7OX/B2f8Ptf8KRJ8W/hx4q0HX" +
                    "lTZcXfhNoLyyvXIyWWOd43gU/3My/7TNXl+L3gpmWIzirm2XUXWo1b3UW1KDlLnkrJNv943JSUKmk3GU" +
                    "Y2jJ65TnFL2CoVZcso7PdM/Rj4f8A7Tn/AAvT4g2dn8Nlg1/wRbea+veLI2b+zLn5X8q106VfkvJfN2M" +
                    "8sW6KJUdd/muqr4n/AMFjv+Cmmmf8E5/hb4Rk8+C58U+LNSJtrJFEjyWEULmSZgeABLJEFb+MSHurV8v" +
                    "ftB/8HZ/ww0HwxOPhf8O/GfiLXmTbBJ4pa3sbC3f+FmSB5HlUf3Mp/vLX4w/td/tc+Pf23vjXqfj/AOI" +
                    "msya3ruo7YkwPLt7GBSxS3t4+kcS7mIUdWZmYs7MzcXhp4B43E4vmzzDOGESs4Sbbmubmsr8sk3OzlJw" +
                    "p+7HljGXM5RrMs7p06bjQlzTfXov69X6n/9k=\" />\r\n</a></td><td><a href=\"");
            
            #line 3 "C:\Users\mg\Documents\Projects\Datahalland\dh-helpdesk\dhHelpdeskNG\dhHelpdesk_NG.Service\BusinessLogic\MailTools\TemplateFormatters\SurveyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VoteNormalLink));
            
            #line default
            #line hidden
            this.Write("\">\r\n\t<img alt=\"");
            
            #line 4 "C:\Users\mg\Documents\Projects\Datahalland\dh-helpdesk\dhHelpdeskNG\dhHelpdesk_NG.Service\BusinessLogic\MailTools\TemplateFormatters\SurveyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VoteNormalText));
            
            #line default
            #line hidden
            this.Write("\" src=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEBLAEsAAD/2wBDAAIBAQIBAQICAgICAgI" +
                    "CAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgM" +
                    "DAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz" +
                    "/wAARCAAfAB8DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgE" +
                    "DAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJic" +
                    "oKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqK" +
                    "jpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwE" +
                    "AAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJ" +
                    "BUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVld" +
                    "YWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcb" +
                    "HyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD8WP2Rv2RPHn7bvxq0/wA" +
                    "A/DnRJdc17UFaSTLeVa2NuMb7m4lOEhiTcvJOSxRQGZlU/sn8Bv8Ag0q+G+h+GIW+KXxM8YeIdekUPPb" +
                    "+FIoNNtbR8fMiyXUcpnQHo22JyOsak4Hr3/Bsz+y7o/wS/wCCcun+PY7OL/hJvi1qF1f3l26qJ47K0nl" +
                    "tYbbJ6IGjeX/aF2c8Kte/fsc/tE/Fb4v/ALX37T3hHx14YTR/Bfwz8UadpXgu8XTWt/tttJDcFyZetwZ" +
                    "Io7a5LDOw3J6I0ar/ADP4keJ2dRljqPD04U44KKc3JrmleXK0lZ7NPbor31R9Nl+W0IxpyxCcnN6Loj4" +
                    "M/aa/4NK/DN94euLn4L/ErXrPWoUJt9L8ZRxXMN4/937XaxR+UTjj93MeeQoy1fjJ8dvgV4u/Zo+LOte" +
                    "B/Hmh3fhvxNoMwhvbK5AJQlQ6OrKSskboyukiEo6OjKWUgn+pD49ftE/FLwR/wUb+AHw38N+F49Q+F/j" +
                    "7S9buvFOqfYfO8t7a3dkUz4KwCErby9R5pugh5K18T/8AB2D+y7pfi39m7wN8Y7W1SPxN4X1xPC17dbM" +
                    "SXlhcQyzx+ax5bypUAXPJa6mPQivR8M/EnN6tbBYPiCcKjxUOeDja8dWrS23dl1d3uRmOXUXGdTDprkd" +
                    "mnt6o9g/4Npf2mNF+M/8AwTO0rwdHdRLr/wAI9QvNM1C23fvVtbu4lvYLvbg4RvNkjGeB9klYkAA19he" +
                    "N/j14m8M+JLjTbf4QfE7xHaWZCw32m3WgrZSggE+Us+pxSrhiQQ8aHIPBG0n+VH9in9tf4hfsC/G+z8e" +
                    "fDnWE03VoUNtdW06GWy1W3LK721xHkboyyIcghlYK6MrqrD9mvgV/wdifB3xF4Xt/+FkfD3x94T1tUVZ" +
                    "U8Oi11TT52CgFw0skLxqSDiMRsVGAXfrXx3it4K5his1qZvlNGNaNW/NCTkkm3e75JRb1vbfR7aJvryv" +
                    "OKXso0a8nFx2dr/52P0a+Hnxu8ReM9fOm3vwt+Ivg6zmid5L/AFm60VrMlQSqMtrqE8hJPQiMgEc4Ga/" +
                    "OL/g68/aT0vwf+yx4H+EcF5G3ifxdr6eJbm2LANb6fawy24d1P3FlnZCgwDut51PKVmftK/8AB2b8PfD" +
                    "XheeH4QfDvxR4g1+RSILzxa8VlY2L4ysnlW7yST4YAbd0JHVZBk1+LX7Sf7RvjT9rL4xax498fa3P4g8" +
                    "Ua5KHubiVQixqAAkcaLhI41XAVEAVQMAV6Hg/4OY7Lc1jnebUo0lBWjCMpNetpSk1q7vVO6Wm7M82zal" +
                    "Kk6FJ3b3f6dD/2Q==\" />\r\n</a></td><td><a href=\"");
            
            #line 5 "C:\Users\mg\Documents\Projects\Datahalland\dh-helpdesk\dhHelpdeskNG\dhHelpdesk_NG.Service\BusinessLogic\MailTools\TemplateFormatters\SurveyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VoteBadLink));
            
            #line default
            #line hidden
            this.Write("\">\r\n\t<img alt=\"");
            
            #line 6 "C:\Users\mg\Documents\Projects\Datahalland\dh-helpdesk\dhHelpdeskNG\dhHelpdesk_NG.Service\BusinessLogic\MailTools\TemplateFormatters\SurveyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VoteBadText));
            
            #line default
            #line hidden
            this.Write("\" src=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgI" +
                    "CAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgM" +
                    "DAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz" +
                    "/wAARCAAfAB4DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgE" +
                    "DAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJic" +
                    "oKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqK" +
                    "jpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwE" +
                    "AAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJ" +
                    "BUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVld" +
                    "YWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcb" +
                    "HyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD84/8Agkf/AMEXPGX/AAU" +
                    "61m91qW/bwX8LdCuBban4hmtvPkubjarfZbOIkCWYKyF2JCxrIpw7NHHJ+ynw5/4Nyv2Rfh94dj0+6+H" +
                    "eseNLgLtk1LXfFF9FdytnHK2jww/98xrX0h+wx8AtP/Ze/Y++FvgHQ4LGBfDfh62EjMm2G41GVd1xPL3" +
                    "2vcGSVsZO2V1HBGOA/wCCT1t8dbb9jDTV/aMbVG+JLa5qbZ1JozefYWmxEZTHxkP5/l46Q+SFwnl1/Gv" +
                    "iP4pZ3icPjMflGLjRp4acYqne05qW0u9tn5XsfZZfl2HpyhTqQcpSTbfRW6Hxv+27/wAGsXw28feFr7V" +
                    "PgPrOo+CfFUKu9voGs3jX+jX5TP7iOZwbi3br+8eSUdtijc4/Cn4pfDHxB8DviNrXhTxRpeoaH4i0G6e" +
                    "y1CwmHly2syHDK2OD2II4IORxX9T/AMI4Pjx/w8/+M8niiS8P7PP/AAiWjL4NB8sWv9pbbfzvs/8AGJB" +
                    "KNS83PQm3JwPIr4z/AOC13/BJofttf8FAvAuqeH5rTSdY8V+CdRn1Z1iCi7l0m7sbbzW6DcU1GKIY6Jb" +
                    "IOTmvuOCfFGtl1RYLiPFRrR9jGr7Ra8t03yytvZJ37adzhx2WwqQ9th4uL5rNPr5o+1v+CWX7Ulj+2D+" +
                    "wj8P/ABNBeW9zrWi6VBoPiMK4b7PfWqCN5TjokgImUnhUlUHo2zY0G1+Knx2t7vxDH4mvPhVos0jDQtI" +
                    "/sO3utUmhDYS51L7XG/l+YAHFrCIZIkIV5GlJEX8yf7DX/BRb4of8E8fif/wkPw61xrM3Sxxahpl0vna" +
                    "fqcSksqSxE4yNzbXXa6b2KsrHI/Urwr/wdyaXB4ZtZNa+Bsd9qmwLcf2V4oksYQ5GRiNrZsJ7eYxr5Pj" +
                    "7wHzJ5lVzDI4wl7V7ys+Vb8qi9H0XN0SstzqwGdUpUo08RdNK2nX1P1U+Cni3xdrt7qvh/wAa6HHZ+I/" +
                    "D8kX/ABNdOhlj0XXbeQMI57dpC7xMPLdJrZnZomALPJHLFK/5X/8ABTL/AILa6Z8Bv+CqxtvCdxDrWlf" +
                    "DPwheeEL2eJFkik1a5vbS4vQvb92LS3ibuJIpR0xXzt+21/wc+/F79oLwXeeF/hx4f0/4PaPqEYhuL6z" +
                    "v5NQ15kPG1LxlQQgjkOkfmr2kFfmRPL9pLSSNu5wSThicZ9++T7k19R4d+A9LCUsRVzqEf30eV04O6V1" +
                    "Zu/RPWyvom10Rz5hnnNanQvaLvd9T/9k=\" />\r\n</a></td></tr></table>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class SurveyTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
