namespace DH.Helpdesk.Common.Enums.Settings
{
    public enum CaseSolutionFields
    {
        UserNumber = 1,
        Department = 2,
        Email = 3,
        CaseType = 4,
        ProductArea = 5,
        Category = 6,
        Caption = 7,
        Description = 8,
        Miscellaneous = 9,
        WorkingGroup = 10,
        Administrator = 11,
        Priority = 12,
        Project = 13,
        ExternalLogNote = 14,
        InternalLogNote = 15,
        FinishingCause = 16,
        PersonsName = 17,
        PersonsPhone = 18,
        PersonsCellPhone = 19,
        Region = 20,
        OU = 21,
        Place = 22,
        Usercode = 23,
        System = 24,
        Urgency = 25,
        Impact = 26,
        InvoiceNumber = 27,
        ReferenceNumber = 28,
        Status = 29,
        StateSecondary = 30,
        Verified = 31,
        VerifiedDescription = 32,
        SolutionRate = 33,
        InventoryNumber = 34,
        InventoryType = 35,
        InventoryLocation = 36,
        Supplier = 37,
        SMS = 38,
        Available = 39,
        Cost = 40,
        ContactBeforeAction = 41,
        Problem = 42,
        Change = 43,
        WatchDate = 44,
        FinishingDate = 45,
        FinishingDescription = 46,
        UpdateNotifierInformation = 47,
        PlanDate = 48,
        CausingPart = 49,
        FileName = 50,
        Source = 51,
        AddUserBtn = 52
    }
}