namespace DH.Helpdesk.BusinessData.Enums.Admin.Users
{
    public enum UserPermission
    {
        Performer,
        CreateCasePermission,
        CopyCasePermission,
        DeleteCasePermission,
        DeleteAttachedFilePermission,
        MoveCasePermission,
        ActivateCasePermission,
        CloseCasePermission,
        RestrictedCasePermission,
        FollowUpPermission,
        DataSecurityPermission,
        CaseSolutionPermission,
        ReportPermission,
        FaqPermission,
        CalendarPermission,
        CreateOrderPermission,
        AdministerOrderPermission,
        CreateSubCasePermission,
        DocumentPermission,
        BulletinBoardPermission,
        InventoryPermission,
        ContractPermission,
        InvoicePermission,
        CaseUnlockPermission,
        CaseInternalLogPermission
    }
}