namespace DH.Helpdesk.Common.Constants
{
    public enum FeatureToggleTypes
    {
        REPORTS_REPORTGENERATOR_USE_PREVIOUS_SEARCH,
        NEW_ADVANCED_CASE_SEARCH,
        NEW_REPORTED_TIME_REPORT,
        NEW_NUMBER_OF_CASES_REPORT,
		FILE_SEARCH_IDX_SERVICE,
		DISABLE_LOG_VIEW_CASE_FILE
	}
}
