using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DH.Helpdesk.Dal.DbQueryExecutor;
using DH.Helpdesk.Dal.Infrastructure;
using DH.Helpdesk.Dal.NewInfrastructure;
using DH.Helpdesk.Dal.NewInfrastructure.Concrete;
using Ninject.Modules;
using DH.Helpdesk.Dal.Repositories;
using DH.Helpdesk.Dal.Repositories.ActionSetting;
using DH.Helpdesk.Dal.Repositories.ActionSetting.Concrete;
using DH.Helpdesk.Dal.Repositories.Computers;
using DH.Helpdesk.Dal.Repositories.Computers.Concrete;
using DH.Helpdesk.Dal.Repositories.MailTemplates;
using DH.Helpdesk.Dal.Repositories.MailTemplates.Concrete;
using DH.Helpdesk.Dal.Repositories.Notifiers;
using DH.Helpdesk.Dal.Repositories.Notifiers.Concrete;
using DH.Helpdesk.Dal.Repositories.Problem;
using DH.Helpdesk.Dal.Repositories.Projects;
using DH.Helpdesk.Dal.Repositories.Projects.Concrete;
using DH.Helpdesk.Dal.Repositories.Users;
using DH.Helpdesk.Dal.Repositories.Users.Concrete;
using DH.Helpdesk.Dal.Repositories.WorkstationModules;
using DH.Helpdesk.Dal.Repositories.WorkstationModules.Concrete;
using DH.Helpdesk.Dal.Repositories.ADFS;
using DH.Helpdesk.Dal.Repositories.ADFS.Concrete;
using DH.Helpdesk.Dal.Repositories.Concrete;
using DH.Helpdesk.Dal.Repositories.Problem.Concrete;
using DH.Helpdesk.Dal.Repositories.Invoice;
using DH.Helpdesk.Dal.Repositories.Invoice.Concrete;
using DH.Helpdesk.Dal.Repositories.Cases;
using DH.Helpdesk.Dal.Repositories.Cases.Concrete;
using DH.Helpdesk.Dal.Repositories.BusinessRules;
using DH.Helpdesk.Dal.Repositories.BusinessRules.Concrete;
using DH.Helpdesk.Dal.Repositories.Faq;
using DH.Helpdesk.Dal.Repositories.Faq.Concrete;
using DH.Helpdesk.Dal.Repositories.Questionnaire;
using DH.Helpdesk.Dal.Repositories.Questionnaire.Concrete;
using DH.Helpdesk.Dal.Repositories.MetaData;
using DH.Helpdesk.Dal.Repositories.MetaData.Concrete;
using DH.Helpdesk.Dal.Repositories.Condition;
using DH.Helpdesk.Dal.Repositories.Condition.Concrete;
using DH.Helpdesk.Dal.Repositories.Inventory;
using DH.Helpdesk.Dal.Repositories.Inventory.Concrete;
using DH.Helpdesk.Dal.Repositories.Servers;
using DH.Helpdesk.Dal.Repositories.Servers.Concrete;
using DH.Helpdesk.Dal.Repositories.Printers;
using DH.Helpdesk.Dal.Repositories.Printers.Concrete;
using IUnitOfWork = DH.Helpdesk.Dal.Infrastructure.IUnitOfWork;
using UnitOfWork = DH.Helpdesk.Dal.Infrastructure.UnitOfWork;

namespace DH.Helpdesk.WebApi.Infrastructure.Config.DependencyInjection
{
    public class RepositoriesModule: NinjectModule
    {
        public override void Load()
        {
            Bind<IDbQueryExecutor>().To<SqlDbQueryExecutor>();
            Bind<IDbQueryExecutorFactory>().To<SqlDbQueryExecutorFactory>();
            Bind<IDatabaseFactory>().To<DatabaseFactory>();
            Bind<IUnitOfWork>().To<UnitOfWork>();
            Bind<ISessionFactory>().To<HelpdeskSessionFactory>();
            Bind<IUnitOfWorkFactory>().To<UnitOfWorkFactory>();

            Bind<ICircularRepository>().To<CircularRepository>();
            Bind<IQuestionnaireQuestionOptionRepository>().To<QuestionnaireQuestionOptionRepository>();
            Bind<IQuestionnaireQuestionRepository>().To<QuestionnaireQuestionRepository>();
            Bind<IQuestionnaireRepository>().To<QuestionnaireRepository>();

            Bind<ICustomerRepository>().To<CustomerRepository>();
            Bind<ITextRepository>().To<TextRepository>();
            Bind<ILanguageRepository>().To<LanguageRepository>();
            Bind<IReportCustomerRepository>().To<ReportCustomerRepository>();
            Bind<ICaseFieldSettingRepository>().To<CaseFieldSettingRepository>();
            Bind<ICaseFieldSettingLanguageRepository>().To<CaseFieldSettingLanguageRepository>();
            Bind<IReportRepository>().To<ReportRepository>();
            Bind<ISettingRepository>().To<SettingRepository>();
            Bind<IUserRepository>().To<UserRepository>();
            Bind<ICaseRepository>().To<CaseRepository>();
            Bind<ICaseFileRepository>().To<CaseFileRepository>();                                                          
            Bind<ICaseHistoryRepository>().To<CaseHistoryRepository>();                                                          
            Bind<IEmailLogRepository>().To<EmailLogRepository>();                                                          
            Bind<ILogRepository>().To<LogRepository>();                                                          
            Bind<ILogFileRepository>().To<LogFileRepository>();                                                          
            Bind<IFormFieldValueRepository>().To<FormFieldValueRepository>();
            Bind<IRegionRepository>().To<RegionRepository>();
            Bind<ICaseTypeRepository>().To<CaseTypeRepository>();
            Bind<ISupplierRepository>().To<SupplierRepository>();
            Bind<IPriorityRepository>().To<PriorityRepository>();
            Bind<IPriorityLanguageRepository>().To<PriorityLanguageRepository>();
            Bind<IStatusRepository>().To<StatusRepository>();
            Bind<IUserWorkingGroupRepository>().To<UserWorkingGroupRepository>();
            Bind<IProductAreaRepository>().To<ProductAreaRepository>();
            Bind<IMailTemplateRepository>().To<MailTemplateRepository>();
            Bind<IWorkingGroupRepository>().To<WorkingGroupRepository>();
            Bind<IMailTemplateLanguageRepository>().To<MailTemplateLanguageRepository>();
            Bind<IMailTemplateIdentifierRepository>().To<MailTemplateIdentifierRepository>();
            Bind<ICaseSettingRepository>().To<CaseSettingRepository>();
            Bind<IUserGroupRepository>().To<UserGroupRepository>();
            Bind<IInfoTextRepository>().To<InfoTextRepository>();
            Bind<IPriorityImpactUrgencyRepository>().To<PriorityImpactUrgencyRepository>();
            Bind<IDepartmentRepository>().To<DepartmentRepository>();
            Bind<ISystemRepository>().To<SystemRepository>();
            Bind<IOperatingSystemRepository>().To<OperatingSystemRepository>();
            Bind<ICategoryRepository>().To<CategoryRepository>();
            Bind<ICurrencyRepository>().To<CurrencyRepository>();
            Bind<ICountryRepository>().To<CountryRepository>();
            Bind<INotifierFieldSettingRepository>().To<NotifierFieldSettingRepository>();
            Bind<INotifierGroupRepository>().To<NotifierGroupRepository>();
            Bind<INotifierRepository>().To<NotifierRepository>();
            Bind<IComputerUsersBlackListRepository>().To<ComputerUsersBlackListRepository>();
            Bind<IComputerUsersRepository>().To<ComputerUsersRepository>();
            Bind<IComputerRepository>().To<ComputerRepository>();
            Bind<IOrganizationUnitRepository>().To<OrganizationUnitRepository>();
            Bind<IAccountActivityRepository>().To<AccountActivityRepository>();
            Bind<ICustomerUserRepository>().To<CustomerUserRepository>();
            Bind<IOrderTypeRepository>().To<OrderTypeRepository>();
            Bind<IUserRoleRepository>().To<UserRoleRepository>();
            Bind<IDepartmentUserRepository>().To<DepartmentUserRepository>();
            Bind<ILogProgramRepository>().To<LogProgramRepository>();
            Bind<IModuleRepository>().To<ModuleRepository>();
            Bind<IUserModuleRepository>().To<UserModuleRepository>();
            Bind<ICaseSearchRepository>().To<CaseSearchRepository>();
            Bind<IGlobalSettingRepository>().To<GlobalSettingRepository>();
            Bind<IProblemLogRepository>().To<ProblemLogRepository>();
            Bind<IProblemEMailLogRepository>().To<ProblemEMailLogRepository>();
            Bind<IProblemRepository>().To<ProblemRepository>();
            Bind<IImpactRepository>().To<ImpactRepository>();            
            Bind<IFinishingCauseRepository>().To<FinishingCauseRepository>();
            Bind<IFinishingCauseCategoryRepository>().To<FinishingCauseCategoryRepository>();
            Bind<IStateSecondaryRepository>().To<StateSecondaryRepository>();
            Bind<ICaseSolutionRepository>().To<CaseSolutionRepository>();
            Bind<ICaseSolutionCategoryRepository>().To<CaseSolutionCategoryRepository>();
            Bind<ICaseSolutionScheduleRepository>().To<CaseSolutionScheduleRepository>();
            Bind<INotifierFieldSettingLanguageRepository>().To<NotifierFieldSettingLanguageRepository>();
            Bind<IActionSettingRepository>().To<ActionSettingRepository>();
            Bind<IInvoiceArticleUnitRepository>().To<InvoiceArticleUnitRepository>();
            Bind<IInvoiceArticleRepository>().To<InvoiceArticleRepository>();
            Bind<ICaseInvoiceArticleRepository>().To<CaseInvoiceArticleRepository>();            
            Bind<IBulletinBoardRepository>().To<BulletinBoardRepository>();
            Bind<ICaseSolutionSettingRepository>().To<CaseSolutionSettingRepository>();
            Bind<IDocumentRepository>().To<DocumentRepository>();
            Bind<IDocumentCategoryRepository>().To<DocumentCategoryRepository>();
            Bind<IFormRepository>().To<FormRepository>();
            Bind<IADFSRepository>().To<ADFSRepository>();
            Bind<IHolidayRepository>().To<HolidayRepository>();
            Bind<IHolidayHeaderRepository>().To<HolidayHeaderRepository>();
            Bind<IDomainRepository>().To<DomainRepository>();
            Bind<ILinkRepository>().To<LinkRepository>();
            Bind<ICaseLockRepository>().To<CaseLockRepository>();
            Bind<ICalendarRepository>().To<CalendarRepository>();
            Bind<ILinkGroupRepository>().To<LinkGroupRepository>();
            Bind<IUsersPasswordHistoryRepository>().To<UsersPasswordHistoryRepository>();
            Bind<ICaseFilterFavoriteRepository>().To<CaseFilterFavoriteRepository>();
            Bind<ICaseInvoiceSettingsRepository>().To<CaseInvoiceSettingsRepository>();
            Bind<IProjectCollaboratorRepository>().To<ProjectCollaboratorRepository>();
            Bind<IProjectFileRepository>().To<ProjectFileRepository>();
            Bind<IProjectLogRepository>().To<ProjectLogRepository>();
            Bind<IProjectRepository>().To<ProjectRepository>();
            Bind<IProjectScheduleRepository>().To<ProjectScheduleRepository>();
            Bind<IReportFavoriteRepository>().To<ReportFavoriteRepository>();
            Bind<IMail2TicketRepository>().To<Mail2TicketRepository>();
            Bind<IBusinessRuleRepository>().To<BusinessRuleRepository>();
            Bind<IEmailGroupRepository>().To<EmailGroupRepository>();
            Bind<IEmailGroupEmailRepository>().To<EmailGroupEmailRepository>();
            Bind<IFaqRepository>().To<FaqRepository>();
            Bind<IFaqFileRepository>().To<FaqFileRepository>();
            Bind<IQuestionRepository>().To<QuestionRepository>();
            Bind<IFaqCategoryRepository>().To<FaqCategoryRepository>();
            Bind<IFaqCategoryLanguageRepository>().To<FaqCategoryLanguageRepository>();
            Bind<IUrgencyRepository>().To<UrgencyRepository>();
            Bind<ICaseExtraFollowersRepository>().To<CaseExtraFollowersRepository>();
            Bind<IUserEmailRepository>().To<UserEmailRepository>();
            Bind<IOrderEMailLogRepository>().To<OrderEMailLogRepository>();
            Bind<IOrderFieldSettingsRepository>().To<OrderFieldSettingsRepository>();
            Bind<IOrderLogRepository>().To<OrderLogRepository>();
            Bind<IOrderRepository>().To<OrderRepository>();
            Bind<IOrderStateRepository>().To<OrderStateRepository>();
            Bind<IExtendedCaseFormRepository>().To<ExtendedCaseFormRepository>();
            Bind<IExtendedCaseDataRepository>().To<ExtendedCaseDataRepository>();
            Bind<ITextTranslationRepository>().To<TextTranslationRepository>();
            Bind<ITextTypeRepository>().To<TextTypeRepository>();
            Bind<IExtendedCaseValueRepository>().To<ExtendedCaseValueRepository>();
            Bind<IApplicationRepository>().To<ApplicationRepository>();
            Bind<IEmailLogAttemptRepository>().To<EmailLogAttemptRepository>();
            Bind<IWatchDateCalendarValueRepository>().To<WatchDateCalendarValueRepository>();
            Bind<IWatchDateCalendarRepository>().To<WatchDateCalendarRepository>();
            Bind<IMetaDataRepository>().To<MetaDataRepository>();            
            Bind<IEntityInfoRepository>().To<EntityInfoRepository>();
            Bind<ICaseFollowUpRepository>().To<CaseFollowUpRepository>();
            Bind<IConditionRepository>().To<ConditionRepository>();

            Bind<IInventoryTypeRepository>().To<InventoryTypeRepository>();
            Bind<IServerRepository>().To<ServerRepository>();
            Bind<IPrinterRepository>().To<PrinterRepository>();
            Bind<IInventoryRepository>().To<InventoryRepository>();
            Bind<IInventoryTypePropertyValueRepository>().To<InventoryTypePropertyValueRepository>();
            Bind<IComputerLogRepository>().To<ComputerLogRepository>();
            Bind<IComputerInventoryRepository>().To<ComputerInventoryRepository>();
            Bind<IOperationLogRepository>().To<OperationLogRepository>();
            Bind<IInventoryTypeGroupRepository>().To<InventoryTypeGroupRepository>();
            Bind<IInventoryFieldSettingsRepository>().To<InventoryFieldSettingsRepository>();
            Bind<IInventoryDynamicFieldSettingsRepository>().To<InventoryDynamicFieldSettingsRepository>();
            Bind<IComputerFieldSettingsRepository>().To<ComputerFieldSettingsRepository>();
            Bind<IComputerHistoryRepository>().To<ComputerHistoryRepository>();
            Bind<ILogicalDriveRepository>().To<LogicalDriveRepository>();
            Bind<ISoftwareRepository>().To<SoftwareRepository>();
            Bind<IServerFieldSettingsRepository>().To<ServerFieldSettingsRepository>();
            Bind<IOperationObjectRepository>().To<OperationObjectRepository>();
            Bind<IOperationLogEMailLogRepository>().To<OperationLogEMailLogRepository>();
            Bind<IServerLogicalDriveRepository>().To<ServerLogicalDriveRepository>();
            Bind<IServerSoftwareRepository>().To<ServerSoftwareRepository>();
            Bind<IPrinterFieldSettingsRepository>().To<PrinterFieldSettingsRepository>();
			Bind<ICaseSectionsRepository>().To<CaseSectionsRepository>();
			Bind<IComputerUserCategoryRepository>().To<ComputerUserCategoryRepository>();
        }
    }
}