BEGIN TRAN

UPDATE X SET Exported = NULL FROM CBD_IN_CEM_BU_ADDRESS_T X
WHERE X.Exported IS NOT NULL

UPDATE X SET Exported = NULL FROM CBD_IN_CEM_BU_BANK_ACCOUNT_T X
WHERE X.Exported IS NOT NULL

UPDATE X SET Exported = NULL FROM CBD_IN_CEM_BU_MEDIA_T X
WHERE X.Exported IS NOT NULL

UPDATE X SET Exported = NULL FROM CBD_IN_CEM_BUSINESS_UNIT_T X
WHERE X.Exported IS NOT NULL

UPDATE X SET Exported = NULL FROM CBD_IN_CEM_E_BU_TAX_REG_T X
WHERE X.Exported IS NOT NULL


COMMIT