ALTER TABLE CBD_IN_CEM_BU_ADDRESS_T ADD Exported DATETIME NULL, Expired DATETIME NULL, Created DATETIME NULL
ALTER TABLE CBD_IN_CEM_BU_BANK_ACCOUNT_T ADD Exported DATETIME NULL, Expired DATETIME NULL, Created DATETIME NULL
ALTER TABLE CBD_IN_CEM_BU_MEDIA_T ADD Exported DATETIME NULL, Expired DATETIME NULL, Created DATETIME NULL
ALTER TABLE CBD_IN_CEM_BUSINESS_UNIT_T ADD Exported DATETIME NULL, Expired DATETIME NULL, Created DATETIME NULL
ALTER TABLE CBD_IN_CEM_E_BU_TAX_REG_T ADD Exported DATETIME NULL, Expired DATETIME NULL, Created DATETIME NULL

ALTER TABLE [dbo].[CBD_IN_CEM_BU_ADDRESS_T] ADD  CONSTRAINT [DF_CBD_IN_CEM_BU_ADDRESS_T_Added]  DEFAULT (getutcdate()) FOR [Created]
ALTER TABLE [dbo].[CBD_IN_CEM_BU_BANK_ACCOUNT_T] ADD  CONSTRAINT [DF_CBD_IN_CEM_BU_BANK_ACCOUNT_T_Created]  DEFAULT (getutcdate()) FOR [Created]
ALTER TABLE [dbo].[CBD_IN_CEM_BU_MEDIA_T] ADD  CONSTRAINT [DF_CBD_IN_CEM_BU_MEDIA_T_Created]  DEFAULT (getdate()) FOR [Created]
ALTER TABLE [dbo].[CBD_IN_CEM_BUSINESS_UNIT_T] ADD  CONSTRAINT [DF_CBD_IN_CEM_BUSINESS_UNIT_T_Created]  DEFAULT (getdate()) FOR [Created]
ALTER TABLE [dbo].[CBD_IN_CEM_E_BU_TAX_REG_T] ADD  CONSTRAINT [DF_CBD_IN_CEM_E_BU_TAX_REG_T_Created]  DEFAULT (getdate()) FOR [Created]
