using System.Collections.Generic;
using System.Collections.ObjectModel;
using DH.Helpdesk.BusinessData.OldComponents;

namespace DH.Helpdesk.Web.Common.Constants.Case
{
    public static class CaseFieldsDefaultNames
    {
        public static readonly IReadOnlyDictionary<GlobalEnums.TranslationCaseFields, string> DefaultNames =
            new Dictionary<GlobalEnums.TranslationCaseFields, string>
        {
            { GlobalEnums.TranslationCaseFields.ReportedBy, "Användar ID" },
            { GlobalEnums.TranslationCaseFields.Persons_Name, "Anmälare" },
            { GlobalEnums.TranslationCaseFields.Persons_EMail, "E-post" },
            { GlobalEnums.TranslationCaseFields.Persons_Phone, "Telefon" },
            { GlobalEnums.TranslationCaseFields.Persons_CellPhone, "Mobil" },
            { GlobalEnums.TranslationCaseFields.Region_Id, "Område" },
            { GlobalEnums.TranslationCaseFields.Department_Id, "Avdelning" },
            { GlobalEnums.TranslationCaseFields.OU_Id, "Enhet" },
            { GlobalEnums.TranslationCaseFields.CostCentre, "Kostnadsställe" },
            { GlobalEnums.TranslationCaseFields.Place, "Placering" },
            { GlobalEnums.TranslationCaseFields.UserCode, "Ansvarskod" },
            { GlobalEnums.TranslationCaseFields.UpdateNotifierInformation, "" },
            { GlobalEnums.TranslationCaseFields.IsAbout_UserSearchCategory_Id, "Anmälarkategori" },
            { GlobalEnums.TranslationCaseFields.IsAbout_ReportedBy, "Användar ID" },
            { GlobalEnums.TranslationCaseFields.IsAbout_Persons_Name, "Anmälare" },
            { GlobalEnums.TranslationCaseFields.IsAbout_Persons_EMail, "E-post" },
            { GlobalEnums.TranslationCaseFields.IsAbout_Persons_Phone, "Telefon" },
            { GlobalEnums.TranslationCaseFields.IsAbout_Persons_CellPhone, "Mobil" },
            { GlobalEnums.TranslationCaseFields.IsAbout_Region_Id, "Område" },
            { GlobalEnums.TranslationCaseFields.IsAbout_Department_Id, "Avdelning" },
            { GlobalEnums.TranslationCaseFields.IsAbout_OU_Id, "Enhet" },
            { GlobalEnums.TranslationCaseFields.IsAbout_CostCentre, "Kostnadsställe" },
            { GlobalEnums.TranslationCaseFields.IsAbout_Place, "Placering" },
            { GlobalEnums.TranslationCaseFields.IsAbout_UserCode, "Ansvarskod" },
            { GlobalEnums.TranslationCaseFields.InventoryNumber, "PC Nummer" },
            { GlobalEnums.TranslationCaseFields.ComputerType_Id, "Datortyp beskrivning" },
            { GlobalEnums.TranslationCaseFields.InventoryLocation, "Placering" },
            { GlobalEnums.TranslationCaseFields.CaseNumber, "Ärende" },
            { GlobalEnums.TranslationCaseFields.RegTime, "Registreringsdatum" },
            { GlobalEnums.TranslationCaseFields.ChangeTime, "Ändringsdatum" },
            { GlobalEnums.TranslationCaseFields.User_Id, "Registrerad av" },
            { GlobalEnums.TranslationCaseFields.RegistrationSourceCustomer, "Källa" },
            { GlobalEnums.TranslationCaseFields.CaseType_Id, "Ärendetyp" },
            { GlobalEnums.TranslationCaseFields.ProductArea_Id, "Produktområde" },
            { GlobalEnums.TranslationCaseFields.System_Id, "System" },
            { GlobalEnums.TranslationCaseFields.Urgency_Id, "Brådskandegrad" },
            { GlobalEnums.TranslationCaseFields.Impact_Id, "Påverkan" },
            { GlobalEnums.TranslationCaseFields.Category_Id, "Kategori" },
            { GlobalEnums.TranslationCaseFields.Supplier_Id, "Leverantör" },
            { GlobalEnums.TranslationCaseFields.InvoiceNumber, "Fakturanummer" },
            { GlobalEnums.TranslationCaseFields.ReferenceNumber, "Referensnummer" },
            { GlobalEnums.TranslationCaseFields.Caption, "Rubrik" },
            { GlobalEnums.TranslationCaseFields.Description, "Beskrivning" },
            { GlobalEnums.TranslationCaseFields.Miscellaneous, "Övrigt" },
            { GlobalEnums.TranslationCaseFields.ContactBeforeAction, "Telefonkontakt" },
            { GlobalEnums.TranslationCaseFields.SMS, "SMS" },
            { GlobalEnums.TranslationCaseFields.AgreedDate, "Överenskommet datum" },
            { GlobalEnums.TranslationCaseFields.Available, "Anträffbar" },
            { GlobalEnums.TranslationCaseFields.Cost, "Artikelkostnad" },
            { GlobalEnums.TranslationCaseFields.Filename, "Bifogad fil" },
            { GlobalEnums.TranslationCaseFields.WorkingGroup_Id, "Driftgrupp" },
            { GlobalEnums.TranslationCaseFields.CaseResponsibleUser_Id, "Ansvarig" },
            { GlobalEnums.TranslationCaseFields.Performer_User_Id, "Handläggare" },
            { GlobalEnums.TranslationCaseFields.Priority_Id, "Prioritet" },
            { GlobalEnums.TranslationCaseFields.Status_Id, "Status" },
            { GlobalEnums.TranslationCaseFields.StateSecondary_Id, "Understatus" },
            { GlobalEnums.TranslationCaseFields.Project, "Projekt" },
            { GlobalEnums.TranslationCaseFields.Problem, "ITIL Problem" },
            { GlobalEnums.TranslationCaseFields.CausingPart, "Rotorsak" },
            { GlobalEnums.TranslationCaseFields.Change, "Ändring" },
            { GlobalEnums.TranslationCaseFields.PlanDate, "Planerad åtgärdsdatum" },
            { GlobalEnums.TranslationCaseFields.WatchDate, "Bevakningsdatum" },
            { GlobalEnums.TranslationCaseFields.Verified, "Verifierad" },
            { GlobalEnums.TranslationCaseFields.VerifiedDescription, "Verifierad beskrivning" },
            { GlobalEnums.TranslationCaseFields.SolutionRate, "Lösningsgrad" },
            { GlobalEnums.TranslationCaseFields.FinishingDescription, "Avslutsbeskrivning" },
            { GlobalEnums.TranslationCaseFields.ClosingReason, "Avslutsorsak" },
            { GlobalEnums.TranslationCaseFields.FinishingDate, "Avslutsdatum" },
        };
    }
}