using System.Collections.Generic;
using DH.Helpdesk.BusinessData.OldComponents;

namespace DH.Helpdesk.Web.Common.Constants.Case
{
    public static class CaseFieldsDefaultNames
    {
        public static readonly IReadOnlyDictionary<GlobalEnums.TranslationCaseFields, string> TranslationCaseFieldsToApiNames =
            new Dictionary<GlobalEnums.TranslationCaseFields, string>
        {
            { GlobalEnums.TranslationCaseFields.UserSearchCategory_Id, CaseFieldsNamesApi.UserSearchCategoryId},
            { GlobalEnums.TranslationCaseFields.ReportedBy, CaseFieldsNamesApi.ReportedBy },
            { GlobalEnums.TranslationCaseFields.Persons_Name, CaseFieldsNamesApi.PersonName },
            { GlobalEnums.TranslationCaseFields.Persons_EMail, CaseFieldsNamesApi.PersonEmail },
            { GlobalEnums.TranslationCaseFields.Persons_Phone, CaseFieldsNamesApi.PersonPhone },
            { GlobalEnums.TranslationCaseFields.Persons_CellPhone, CaseFieldsNamesApi.PersonCellPhone },
            { GlobalEnums.TranslationCaseFields.Region_Id, CaseFieldsNamesApi.RegionId },
            { GlobalEnums.TranslationCaseFields.Department_Id, CaseFieldsNamesApi.DepartmentId },
            { GlobalEnums.TranslationCaseFields.OU_Id, CaseFieldsNamesApi.OrganizationUnitId },
            { GlobalEnums.TranslationCaseFields.CostCentre, CaseFieldsNamesApi.CostCentre },
            { GlobalEnums.TranslationCaseFields.Place, CaseFieldsNamesApi.Place },
            { GlobalEnums.TranslationCaseFields.UserCode, CaseFieldsNamesApi.UserCode },
            { GlobalEnums.TranslationCaseFields.UpdateNotifierInformation, "" },
            { GlobalEnums.TranslationCaseFields.IsAbout_UserSearchCategory_Id, CaseFieldsNamesApi.IsAbout_UserSearchCategoryId },
            { GlobalEnums.TranslationCaseFields.IsAbout_ReportedBy, CaseFieldsNamesApi.IsAbout_ReportedBy },
            { GlobalEnums.TranslationCaseFields.IsAbout_Persons_Name, CaseFieldsNamesApi.IsAbout_PersonName },
            { GlobalEnums.TranslationCaseFields.IsAbout_Persons_EMail, CaseFieldsNamesApi.IsAbout_PersonEmail },
            { GlobalEnums.TranslationCaseFields.IsAbout_Persons_Phone, CaseFieldsNamesApi.IsAbout_PersonPhone },
            { GlobalEnums.TranslationCaseFields.IsAbout_Persons_CellPhone, CaseFieldsNamesApi.IsAbout_PersonCellPhone },
            { GlobalEnums.TranslationCaseFields.IsAbout_Region_Id, CaseFieldsNamesApi.IsAbout_RegionId },
            { GlobalEnums.TranslationCaseFields.IsAbout_Department_Id, CaseFieldsNamesApi.IsAbout_DepartmentId },
            { GlobalEnums.TranslationCaseFields.IsAbout_OU_Id, CaseFieldsNamesApi.IsAbout_OrganizationUnitId },
            { GlobalEnums.TranslationCaseFields.IsAbout_CostCentre, CaseFieldsNamesApi.IsAbout_CostCentre },
            { GlobalEnums.TranslationCaseFields.IsAbout_Place, CaseFieldsNamesApi.IsAbout_Place },
            { GlobalEnums.TranslationCaseFields.IsAbout_UserCode, CaseFieldsNamesApi.IsAbout_UserCode },
            { GlobalEnums.TranslationCaseFields.InventoryNumber, CaseFieldsNamesApi.InventoryNumber },
            { GlobalEnums.TranslationCaseFields.ComputerType_Id, CaseFieldsNamesApi.ComputerTypeId },
            { GlobalEnums.TranslationCaseFields.InventoryLocation, CaseFieldsNamesApi.InventoryLocation },
            { GlobalEnums.TranslationCaseFields.CaseNumber, CaseFieldsNamesApi.CaseNumber },
            { GlobalEnums.TranslationCaseFields.RegTime, CaseFieldsNamesApi.RegTime },
            { GlobalEnums.TranslationCaseFields.ChangeTime, CaseFieldsNamesApi.ChangeTime },
            { GlobalEnums.TranslationCaseFields.User_Id, CaseFieldsNamesApi.UserId },
            { GlobalEnums.TranslationCaseFields.RegistrationSourceCustomer, CaseFieldsNamesApi.RegistrationSourceCustomer },
            { GlobalEnums.TranslationCaseFields.CaseType_Id, CaseFieldsNamesApi.CaseTypeId },
            { GlobalEnums.TranslationCaseFields.ProductArea_Id, CaseFieldsNamesApi.ProductAreaId },
            { GlobalEnums.TranslationCaseFields.System_Id, CaseFieldsNamesApi.SystemId },
            { GlobalEnums.TranslationCaseFields.Urgency_Id, CaseFieldsNamesApi.UrgencyId },
            { GlobalEnums.TranslationCaseFields.Impact_Id, CaseFieldsNamesApi.ImpactId },
            { GlobalEnums.TranslationCaseFields.Category_Id, CaseFieldsNamesApi.CategoryId },
            { GlobalEnums.TranslationCaseFields.Supplier_Id, CaseFieldsNamesApi.SupplierId },
            { GlobalEnums.TranslationCaseFields.InvoiceNumber, CaseFieldsNamesApi.InvoiceNumber },
            { GlobalEnums.TranslationCaseFields.ReferenceNumber, CaseFieldsNamesApi.ReferenceNumber },
            { GlobalEnums.TranslationCaseFields.Caption, CaseFieldsNamesApi.Caption },
            { GlobalEnums.TranslationCaseFields.Description, CaseFieldsNamesApi.Description },
            { GlobalEnums.TranslationCaseFields.Miscellaneous, CaseFieldsNamesApi.Miscellaneous },
            { GlobalEnums.TranslationCaseFields.ContactBeforeAction, CaseFieldsNamesApi.ContactBeforeAction },
            { GlobalEnums.TranslationCaseFields.SMS, CaseFieldsNamesApi.Sms },
            { GlobalEnums.TranslationCaseFields.AgreedDate, CaseFieldsNamesApi.AgreedDate },
            { GlobalEnums.TranslationCaseFields.Available, CaseFieldsNamesApi.Available },
            { GlobalEnums.TranslationCaseFields.Cost, CaseFieldsNamesApi.Cost },
            { GlobalEnums.TranslationCaseFields.Filename, CaseFieldsNamesApi.Filename },
            { GlobalEnums.TranslationCaseFields.WorkingGroup_Id, CaseFieldsNamesApi.WorkingGroupId },
            { GlobalEnums.TranslationCaseFields.CaseResponsibleUser_Id, CaseFieldsNamesApi.CaseResponsibleUserId },
            { GlobalEnums.TranslationCaseFields.Performer_User_Id, CaseFieldsNamesApi.PerformerUserId },
            { GlobalEnums.TranslationCaseFields.Priority_Id, CaseFieldsNamesApi.PriorityId },
            { GlobalEnums.TranslationCaseFields.Status_Id, CaseFieldsNamesApi.StatusId },
            { GlobalEnums.TranslationCaseFields.StateSecondary_Id, CaseFieldsNamesApi.StateSecondaryId },
            { GlobalEnums.TranslationCaseFields.Project, CaseFieldsNamesApi.Project },
            { GlobalEnums.TranslationCaseFields.Problem, CaseFieldsNamesApi.Problem },
            { GlobalEnums.TranslationCaseFields.CausingPart, CaseFieldsNamesApi.CausingPart },
            { GlobalEnums.TranslationCaseFields.Change, CaseFieldsNamesApi.Change },
            { GlobalEnums.TranslationCaseFields.PlanDate, CaseFieldsNamesApi.PlanDate },
            { GlobalEnums.TranslationCaseFields.WatchDate, CaseFieldsNamesApi.WatchDate },
            { GlobalEnums.TranslationCaseFields.Verified, CaseFieldsNamesApi.Verified },
            { GlobalEnums.TranslationCaseFields.VerifiedDescription, CaseFieldsNamesApi.VerifiedDescription },
            { GlobalEnums.TranslationCaseFields.SolutionRate, CaseFieldsNamesApi.SolutionRate },
            { GlobalEnums.TranslationCaseFields.FinishingDescription, CaseFieldsNamesApi.FinishingDescription },
            { GlobalEnums.TranslationCaseFields.ClosingReason, CaseFieldsNamesApi.ClosingReason },
            { GlobalEnums.TranslationCaseFields.FinishingDate, CaseFieldsNamesApi.FinishingDate },
            { GlobalEnums.TranslationCaseFields.AddFollowersBtn, CaseFieldsNamesApi.Followers },
        };
    }
}